void logo(){
    printf("\t\t\t\t\t\t                 .\"-,.__                                                \n");
    printf("\t\t\t\t\t\t                 `.     `.  ,                                           \n");
    printf("\t\t\t\t\t\t              .--'  .._,'\"-' `.                                         \n");
    printf("\t\t\t\t\t\t             .    .'         `'                                         \n");
    printf("\t\t\t\t\t\t             `.   /          ,'                                         \n");
    printf("\t\t\t\t\t\t               `  '--.   ,-\"'                                           \n");
    printf("\t\t\t\t\t\t                `\"`   |  \\                                              \n");
    printf("\t\t\t\t\t\t                   -. \\, |                                              \n");
    printf("\t\t\t\t\t\t                    `--Y.'      ___.                                    \n");
    printf("\t\t\t\t\t\t                         \\     L._, \\                                  \n");
    printf("\t\t\t\t\t\t               _.,        `.   <  <\\                _                   \n");
    printf("\t\t\t\t\t\t             ,' '           `, `.   | \\            ( `                  \n");
    printf("\t\t\t\t\t\t          ../, `.            `  |    .\\`.           \\ \\_                \n");
    printf("\t\t\t\t\t\t         ,' ,..  .           _.,'    ||\\l            )  '"".             \n");
    printf("\t\t\t\t\t\t        , ,'   \\           ,'.-.`-._,'  |           .  _._`.            \n");
    printf("\t\t\t\t\t\t      ,' /      \\ \\        `' ' `--/   | \\          / /   ..\\           \n");
    printf("\t\t\t\t\t\t    .'  /        \\ .         |\\__ - _ ,'` `        / /     `.`.         \n");
    printf("\t\t\t\t\t\t    |  '          ..         `-...-\"  |  `-'      / /        . `.       \n");
    printf("\t\t\t\t\t\t    | /           |L__           |    |          / /          `. `.     \n");
    printf("\t\t\t\t\t\t   , /            .   .          |    |         / /             ` `     \n");
    printf("\t\t\t\t\t\t  / /          ,. ,`._ `-_       |    |  _   ,-' /               ` \\    \n");
    printf("\t\t\t\t\t\t / .           \\\"`_/. `-_ \\_,.  ,'    +-' `-'  _,        ..,-.    \\`.  \n");
    printf("\t\t\t\t\t\t.  '         .-f    ,'   `    '.       \\__.---'     _   .'   '     \\ \\ \n");
    printf("\t\t\t\t\t\t' /          `.'    l     .' /          \\..      ,_|/   `.  ,'`     L` \n");
    printf("\t\t\t\t\t\t|'      _.-\"\"` `.    \\ _,'  `            \\ `.___`.'\"\"-.  , |   |    | \\ \n");
    printf("\t\t\t\t\t\t||    ,'      `. `.   '       _,...._        `  |    `/ '  |   '     .|\n");
    printf("\t\t\t\t\t\t||  ,'          `. ;.,.---' ,'       `.   `.. `-'  .-' /_ .'    ;_   ||\n");
    printf("\t\t\t\t\t\t|| ,'            V      / /           `   | `   ,'   ,' '.    !  `. ||\n");
    printf("\t\t\t\t\t\t||/            _,-------7 '              . |  `-'    l         /    `||\n");
    printf("\t\t\t\t\t\t. |          ,' .-   ,' ||               | .-.        `.      .'     ||\n");
    printf("\t\t\t\t\t\t`'        ,'    `\".'    |               |    `.        '. -.'       `' \n");
    printf("\t\t\t\t\t\t         /      ,'      |               |,'    \\-.._,.'/                \n");
    printf("\t\t\t\t\t\t         .     /        .               .       \\    .''                 \n");
    printf("\t\t\t\t\t\t       .`.    |         `.             /         :_,'.'                  \n");
    printf("\t\t\t\t\t\t         \\ `...\\   _     ,'-.        .'         /_.-'                    \n");
    printf("\t\t\t\t\t\t          `-.__ `,  `'   .  _.>--''/        _\\                          \n");
    printf("\t\t\t\t\t\t              .'        /\"'          |  \"'   '_                         \n");
    printf("\t\t\t\t\t\t             /_|.-'\\ ,\".             '.'`__'-( \\                        \n");
    printf("\t\t\t\t\t\t               / ,\"'\"\\,'               `/  `-.|\"                      \n");
}