void logo(){
   printf("\t\t\t\t\t\t\t                  ,-\\`\\                                \n");
    printf("\t\t\t\t\t\t\t                  _,\"'    j                                \n");
    printf("\t\t\t\t\t\t\t           __....+       /               .                 \n");
    printf("\t\t\t\t\t\t\t       ,-\"'             /               ; `-._.'.          \n");
    printf("\t\t\t\t\t\t\t      /                (              ,'       .'          \n");
    printf("\t\t\t\t\t\t\t     |            _.    \\             \\   ---._ `-         \n");
    printf("\t\t\t\t\t\t\t     ,|    ,   _.'  Y    \\             `- ,'   \\   `.`.    \n");
    printf("\t\t\t\t\t\t\t     l'    \\ ,'._,\\ `.    .              /       ,--. l    \n");
    printf("\t\t\t\t\t\t\t  .,-        `._  |  |    |              \\       _   l .   \n");
    printf("\t\t\t\t\t\t\t /              `\"--'    /               .'       ``. |  )  \n");
    printf("\t\t\t\t\t\t\t.\\    ,                 |                .        \\ `. '   \n");
    printf("\t\t\t\t\t\t\t`.                .     |                '._  __   ;. \\'   \n");
    printf("\t\t\t\t\t\t\t  `-..--------...'       \\                  `'  `-\"'.  \\   \n");
    printf("\t\t\t\t\t\t\t      `......___          `._                        |  \\  \n");
    printf("\t\t\t\t\t\t\t               /`            `..                     |   . \n");
    printf("\t\t\t\t\t\t\t              /|                `-.                  |    L\n");
    printf("\t\t\t\t\t\t\t             / |               \\   `._               .    |\n");
    printf("\t\t\t\t\t\t\t           ,'  |,-\"-.   .       .     `.            /     |\n");
    printf("\t\t\t\t\t\t\t         ,'    |     '   \\      |       `.         /      |\n");
    printf("\t\t\t\t\t\t\t       ,'     /|       \\  .     |         .       /       |\n");
    printf("\t\t\t\t\t\t\t     ,'      / |        \\  .    +          \\    ,'       .'\n");
    printf("\t\t\t\t\t\t\t    .       .  |         \\ |     \\          \\_,'        / j\n");
    printf("\t\t\t\t\t\t\t    |       |  L          `|      .          `        ,' ' \n");
    printf("\t\t\t\t\t\t\t    |    _. |   \\          /      |           .     .' ,'  \n");
    printf("\t\t\t\t\t\t\t    |   /  `|    \\        .       |  /        |   ,' .'    \n");
    printf("\t\t\t\t\t\t\t    |   ,-..\\     -.     ,        | /         |,.' ,'      \n");
    printf("\t\t\t\t\t\t\t    `. |___,`    /  `.   /`.       '          |  .'        \n");
    printf("\t\t\t\t\t\t\t      '-`-'     j     ` /.\"7-..../|          ,`-'          \n");
    printf("\t\t\t\t\t\t\t                |        .'  / _/_|          .             \n");
    printf("\t\t\t\t\t\t\t                `,       `\"'/'\"'    \\          `.           \n");
    printf("\t\t\t\t\t\t\t                  `,       '.       `.         |           \n");
    printf("\t\t\t\t\t\t\t             __,.-'         `.        \\'       |           \n");
    printf("\t\t\t\t\t\t\t            /_,-'\\          ,'        |        _\\          \n");
    printf("\t\t\t\t\t\t\t             |___.---.   ,-'        .-':,-\"`\\,' .          \n");
    printf("\t\t\t\t\t\t\t                  L,.--\"'           '-' |  ,' `-\\.         \n");
    printf("\t\t\t\t\t\t\t                                        `.' \n");
}